name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build_release
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 8
      matrix:
        device:
          - dumpling
          - cheeseburger
          - chiron
          - nash
          - joan
          - sagit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install requires packages
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential uuid-dev iasl nasm gcc-aarch64-linux-gnu abootimg python3-distutils python3-pil python3-git gettext

      - name: Build device ${{ matrix.device }}
        run: |
          ./build.sh --device ${{ matrix.device }}
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: To be filled. 待填充
          files: boot-${{ matrix.device }}.img
